version: "2.2"

services:
  # zookeeper:
  #   restart: always
  #   container_name: zookeeper
  #   hostname: zookeeper
  #   image: wurstmeister/zookeeper:3.4.6
  #   ports:
  #     - "2181:2181"
  # kafka:
  #   restart: always
  #   container_name: kafka
  #   hostname: kafka
  #   image: wurstmeister/kafka:2.12-2.3.0
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - "9092:9092"
  #     - "9093:9093"
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_CREATE_TOPICS: "Modusign-Document-Task-v1:1:1,Modusign-Document-TaskDlt-v1:1:1"
  #     KAFKA_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://:9093
  #     KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9093
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:SASL_PLAINTEXT,EXTERNAL:SASL_PLAINTEXT
  #     KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
  #     KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
  #     KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - .kafka/kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf
  lambda:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      - NODE_ENV=development
      - DD_ENV=development
      # for Datadog test
      - DD_TRACE_ENABLED=true
      - DD_FLUSH_TO_LOG=true
      - DD_SERVERLESS_LOGS_ENABLED=true
      - DD_API_KEY=
    ports:
      - "9000:8080"
    # depends_on:
    #   - zookeeper
    #   - kafka
  
